export const Data =[
    {"id":1,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"card.jpg","type":"img"},
{"id":2,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"blog.png","type":"img"},
{"id":3,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"post.webp","type":"vdo"},
{"id":4,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"card.jpg","type":"img"},
{"id":5,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"card.jpg","type":"img"},
{"id":6,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"card.jpg","type":"img"},
{"id":7,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"card.jpg","type":"img"},
{"id":8,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"card.jpg","type":"img"},
{"id":10,"title":"Why Startups Must Liberate From Hiring Platforms","date":"16 November 2021","para":"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal","img":"card.jpg","type":"img"},
];
export function getData() {
    return Data;
  }